export enum ErrorType {
	NO_SESSION_ID = "NO_SESSION_ID",
	BIOMETRIC_DUPLICATE_ACCOUNT = "BIOMETRIC_DUPLICATE_ACCOUNT",
	USER_NOT_FOUND = "USER_NOT_FOUND",
	BVN_ALREADY_EXIST = "BVN_ALREADY_EXIST",
	BVN_DOES_NOT_EXIST = "BVN_DOES_NOT_EXIST",
	FACE_MISMATCH = "FACE_MISMATCH",
}
