export enum ErrorType {
	NO_SESSION_ID = "NO_SESSION_ID",
	BIOMETRIC_DUPLICATE_ACCOUNT = "BIOMETRIC_DUPLICATE_ACCOUNT",
	USER_NOT_FOUND = "USER_NOT_FOUND",
	BVN_ALREADY_EXISTS = "BVN_ALREADY_EXISTS",
}
